sylius_ui:
    events:
        sylius.shop.layout.after_body:
            blocks:
                monsieurbiz_markerio_metadata:
                    template: '@MonsieurBizSyliusMarkerioPlugin/Shop/render.html.twig'
                    priority: 10
        sylius.admin.layout.javascripts:
            blocks:
                monsieurbiz_markerio_metadata:
                    template: '@MonsieurBizSyliusMarkerioPlugin/metadata.html.twig'
                    priority: 10

monsieurbiz_sylius_settings:
    plugins:
        monsieurbiz.markerio:
            vendor_name: Monsieur Biz
            vendor_url: https://monsieurbiz.com/
            plugin_name: monsieurbiz_sylius_markerio_plugin.settings.plugin_name
            description: monsieurbiz_sylius_markerio_plugin.settings.description
            icon: paper plane outline
            use_locales: false
            classes:
                form: MonsieurBiz\SyliusMarkerioPlugin\Form\Type\MarkerioSettingsType
