services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusMarkerioPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations}'

    MonsieurBiz\SyliusMarkerioPlugin\Controller\:
        resource: '../../Controller'
        tags: [ 'controller.service_arguments' ]

    MonsieurBiz\SyliusMarkerioPlugin\EventListener\MarkerioCustomDataListener:
        tags:
            - { name: kernel.event_listener, event: MonsieurBiz\SyliusMarkerioPlugin\Event\MarkerioCustomDataEvent, method: appendCustomData }
