services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusMarkerioPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations}'
